/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description: 'Learn how to install and start using the CIFER SDK.',
        slug: '/getting-started',
      },
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/quick-start-web2',
        'getting-started/concepts',
      ],
    },
    {
      type: 'category',
      label: 'Web3 Guides',
      link: {
        type: 'generated-index',
        title: 'Web3 Guides',
        description: 'Task-oriented guides for wallet-based (Web3) usage of CIFER.',
        slug: '/guides/web3',
      },
      collapsed: false,
      items: [
        'guides/web3/wallet-integration',
        'guides/web3/secret-management',
        'guides/web3/text-encryption',
        'guides/web3/file-encryption',
        'guides/web3/commitments',
        'guides/web3/flows',
      ],
    },
    {
      type: 'category',
      label: 'Web2 Guides',
      link: {
        type: 'generated-index',
        title: 'Web2 Guides',
        description: 'Task-oriented guides for email + password (Web2) usage of CIFER.',
        slug: '/guides/web2',
      },
      collapsed: false,
      items: [
        'guides/web2/authentication',
        'guides/web2/secret-management',
        'guides/web2/text-encryption',
        'guides/web2/file-encryption',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'doc',
        id: 'api/index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    'changelog',
  ],
};

module.exports = sidebars;
